import js from '@eslint/js';
import globals from 'globals';
import reactPlugin from 'eslint-plugin-react';
import reactHooksPlugin from 'eslint-plugin-react-hooks';
import importPlugin from 'eslint-plugin-import';
import jsxA11yPlugin from 'eslint-plugin-jsx-a11y';
import unusedImportsPlugin from 'eslint-plugin-unused-imports';

/**
 * ESLint flat config for Research Hub projects.
 * Generated by hub-gen.mjs scaffold — shared across all hub instances.
 *
 * Rule rationale is documented inline. Every suppression is intentional.
 * If you change a rule, update the comment explaining why.
 */
export default [
  js.configs.recommended,

  {
    files: ['src/**/*.{js,jsx}'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.es2021,
      },
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
    },
    plugins: {
      react: reactPlugin,
      'react-hooks': reactHooksPlugin,
      import: importPlugin,
      'jsx-a11y': jsxA11yPlugin,
      'unused-imports': unusedImportsPlugin,
    },
    settings: {
      react: { version: 'detect' },
      'import/resolver': {
        node: { extensions: ['.js', '.jsx'] },
      },
    },
    rules: {
      // ── Core ──
      'no-undef': 'error',
      // Empty catch blocks are valid for graceful degradation (e.g. localStorage).
      // Other empty blocks (if/for) are still flagged.
      'no-empty': ['warn', { allowEmptyCatch: true }],

      // ── Unused code ──
      // Built-in no-unused-vars is OFF — replaced by unused-imports plugin which
      // provides auto-fix and better destructuring support (ignoreRestSiblings).
      'no-unused-vars': 'off',
      // Auto-removes dead imports on --fix.
      'unused-imports/no-unused-imports': 'warn',
      // Catches unused vars/args. Prefix with _ to mark intentionally unused.
      'unused-imports/no-unused-vars': ['warn', {
        vars: 'all', varsIgnorePattern: '^_', argsIgnorePattern: '^_',
        ignoreRestSiblings: true,
      }],

      // ── React ──
      // Prevents ESLint from false-flagging React/component usage in JSX.
      'react/jsx-uses-react': 'error',
      'react/jsx-uses-vars': 'error',
      // No PropTypes — project uses neither TypeScript nor runtime prop validation.
      'react/prop-types': 'off',
      // Content-heavy dashboards have many apostrophes; escaping adds noise.
      'react/no-unescaped-entities': 'off',
      // React 17+ JSX transform does not require React in scope.
      'react/react-in-jsx-scope': 'off',

      // ── React Hooks ──
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',

      // ── Imports ──
      // Resolver cannot follow the hub's relative project paths without extra config.
      'import/no-unresolved': 'off',
      'import/named': 'warn',

      // ── Accessibility ──
      // Interactive dashboard cards use onClick on non-button elements by design.
      // Core a11y rules remain active; only the noisy dashboard-specific ones are off.
      'jsx-a11y/click-events-have-key-events': 'off',
      'jsx-a11y/no-static-element-interactions': 'off',
      'jsx-a11y/anchor-is-valid': 'off',
      'jsx-a11y/no-noninteractive-element-interactions': 'off',
    },
  },

  {
    ignores: ['dist/**', 'node_modules/**', 'vite.config.js', 'tailwind.config.js', 'postcss.config.js'],
  },
];
