// Research Hub — generated by research-visualizer v8.12
import React, { useState } from 'react';
import { BarChart3, ChevronRight, FileText, Globe, Lightbulb } from 'lucide-react';

import Overview from './components/Overview';
import ComparisonTable from './components/ComparisonTable';
import ValueScatter from './components/ValueScatter';
import FeatureMatrix from './components/FeatureMatrix';
import UseCaseFit from './components/UseCaseFit';
import Recommendations from './components/Recommendations';
import Sources from './components/Sources';

const SECTIONS = [
  { key: 'overview', label: 'Overview', icon: BarChart3, component: Overview },
  { key: 'comparisontable', label: 'Comparison Table', icon: FileText, component: ComparisonTable },
  { key: 'valuescatter', label: 'Value vs. Price', icon: BarChart3, component: ValueScatter },
  { key: 'featurematrix', label: 'Feature Matrix', icon: FileText, component: FeatureMatrix },
  { key: 'usecasefit', label: 'Use Case Fit', icon: BarChart3, component: UseCaseFit },
  { key: 'recommendations', label: 'Recommendations', icon: Lightbulb, component: Recommendations },
  { key: 'sources', label: 'Sources', icon: Globe, component: Sources },
];

export default function App() {
  const [activeSection, setActiveSection] = useState(SECTIONS[0].key);
  const ActiveComponent = SECTIONS.find(s => s.key === activeSection)?.component || SECTIONS[0].component;

  return (
    <div className="flex h-full bg-gray-950 text-white">
      {/* Sidebar */}
      <nav className="w-56 flex-shrink-0 border-r border-gray-800 bg-gray-950/50 overflow-y-auto">
        <div className="p-4">
          <h1 className="text-base font-bold text-white mb-0.5">USB Desktop Microphone Finder</h1>
          <p className="text-xs text-gray-400 mb-4">9 Mics, 4 Price Tiers, Real Prices — Plug-In-and-Go for WebEx, Recording & Streaming</p>
          <h2 className="text-sm font-semibold text-gray-400 uppercase tracking-wider mb-3">Sections</h2>
          <ul className="space-y-1">
            {SECTIONS.map(s => {
              const Icon = s.icon;
              return (
                <li key={s.key}>
                  <button
                    onClick={() => setActiveSection(s.key)}
                    className={`w-full flex items-center gap-2 px-3 py-2 rounded-lg text-sm transition-colors cursor-pointer ${
                      activeSection === s.key
                        ? 'bg-indigo-500/20 text-indigo-300'
                        : 'text-gray-400 hover:text-white hover:bg-gray-800/50'
                    }`}
                  >
                    <Icon className="w-4 h-4" />
                    {s.label}
                    {activeSection === s.key && <ChevronRight className="w-3 h-3 ml-auto" />}
                  </button>
                </li>
              );
            })}
          </ul>
        </div>
      </nav>

      {/* Main content */}
      <main className="flex-1 overflow-y-auto">
        <div className="max-w-5xl mx-auto px-6 py-8">
          <ActiveComponent />
        </div>
      </main>
    </div>
  );
}
