import React, { useState, useRef, useEffect } from 'react';
import { Copy, Check } from 'lucide-react';

/**
 * Shared GlossaryTerm component — used by all projects.
 * Generated by hub-gen.mjs install-components. Do not edit manually.
 *
 * Usage in project components:
 *   import { GlossaryTerm } from '../../components/GlossaryTerm';
 *   <GlossaryTerm term="MCP" glossary={glossaryTerms}>Model Context Protocol</GlossaryTerm>
 *
 * The `glossary` prop is a map of term → { definition, researchPrompt }.
 * Each project passes its own glossaryTerms data.
 */
export function GlossaryTerm({ term, children, glossary, accentColor = 'indigo' }) {
  const [open, setOpen] = useState(false);
  const [copied, setCopied] = useState(false);
  const [flipUp, setFlipUp] = useState(false);
  const ref = useRef(null);
  const flyoutRef = useRef(null);

  const data = glossary?.[term];

  useEffect(() => {
    if (!open) return;
    const handleClick = (e) => {
      if (ref.current && !ref.current.contains(e.target)) setOpen(false);
    };
    const handleKey = (e) => { if (e.key === 'Escape') setOpen(false); };
    document.addEventListener('mousedown', handleClick);
    document.addEventListener('keydown', handleKey);
    return () => {
      document.removeEventListener('mousedown', handleClick);
      document.removeEventListener('keydown', handleKey);
    };
  }, [open]);

  useEffect(() => {
    if (open && flyoutRef.current) {
      const rect = flyoutRef.current.getBoundingClientRect();
      setFlipUp(rect.bottom > window.innerHeight);
    }
  }, [open]);

  if (!data) return <>{children}</>;

  const handleCopy = (e) => {
    e.stopPropagation();
    navigator.clipboard.writeText(data.researchPrompt);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <span ref={ref} className="relative inline">
      <span
        onClick={() => setOpen(!open)}
        className={`border-b border-dotted border-${accentColor}-500/40 cursor-pointer hover:border-solid hover:bg-${accentColor}-500/10 transition-colors`}
      >
        {children}
      </span>
      {open && (
        <div
          ref={flyoutRef}
          className={`absolute z-50 ${flipUp ? 'bottom-full mb-2' : 'top-full mt-2'} left-0 bg-gray-800 border border-gray-700 rounded-lg shadow-xl p-4 w-[360px]`}
        >
          <p className="text-sm font-bold text-white mb-1.5">{term}</p>
          <p className="text-xs text-gray-300 leading-relaxed mb-3">{data.definition}</p>
          <p className="text-[10px] text-gray-500 uppercase tracking-wider mb-1">Deep dive with Research Visualizer:</p>
          <div className="bg-gray-950 border border-gray-700 rounded-lg px-3 py-2 flex items-start gap-2">
            <p className="font-mono text-[11px] text-gray-300 leading-relaxed flex-1">{data.researchPrompt}</p>
            <button onClick={handleCopy} className="text-gray-500 hover:text-white cursor-pointer flex-shrink-0 mt-0.5">
              {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
            </button>
          </div>
        </div>
      )}
    </span>
  );
}
