import React from 'react';
import { Lightbulb } from 'lucide-react';

/**
 * Shared InsightCallout component — used by all projects.
 * Generated by hub-gen.mjs install-components. Do not edit manually.
 *
 * Usage in project components:
 *   import InsightCallout from '../../components/InsightCallout';
 *   <InsightCallout color="emerald">Key insight here</InsightCallout>
 */
export default function InsightCallout({ children, color = 'violet' }) {
  const colorMap = {
    violet: 'border-violet-500/30 bg-violet-500/5 text-violet-300',
    amber: 'border-amber-500/30 bg-amber-500/5 text-amber-300',
    emerald: 'border-emerald-500/30 bg-emerald-500/5 text-emerald-300',
    blue: 'border-blue-500/30 bg-blue-500/5 text-blue-300',
    red: 'border-red-500/30 bg-red-500/5 text-red-300',
    cyan: 'border-cyan-500/30 bg-cyan-500/5 text-cyan-300',
    orange: 'border-orange-500/30 bg-orange-500/5 text-orange-300',
    indigo: 'border-indigo-500/30 bg-indigo-500/5 text-indigo-300',
    rose: 'border-rose-500/30 bg-rose-500/5 text-rose-300',
    teal: 'border-teal-500/30 bg-teal-500/5 text-teal-300',
    purple: 'border-purple-500/30 bg-purple-500/5 text-purple-300',
  };
  return (
    <div className={`border rounded-lg px-4 py-3 text-sm flex items-start gap-3 ${colorMap[color] || colorMap.violet}`}>
      <Lightbulb className="w-4 h-4 flex-shrink-0 mt-0.5 opacity-70" />
      <div>{children}</div>
    </div>
  );
}
