import { lazy } from 'react';

export const projectRegistry = [
  {
    slug: 'cisco-history-dashboard',
    title: 'Cisco History Dashboard',
    subtitle: '40 Years of Innovation',
    query: 'Research the history of Cisco Systems from founding to present day',
    lens: 'standard',
    icon: 'Building2',
    accentColor: 'cyan',
    createdAt: '2026-02-08T12:00:00Z',
    telemetry: {
      runStartedAt: '2026-02-08T12:00:00Z',
      runCompletedAt: '2026-02-08T14:00:00Z',
      durationMinutes: 120,
      includedSetup: true,
      skillVersion: '3.0',
      userPrompt: 'Research the history of Cisco Systems from founding to present day',
      researchPlan: 'TOPIC: Cisco Systems Corporate History\nTIME AXIS: Decades — 1984-2026\nPOPULATIONS: Cisco as corporation, leadership eras, acquired companies\nCORE METRICS: Revenue, market cap, employee count, acquisitions\nTAXONOMIES: CEO eras (5), major acquisitions (20+), product lines\nPROPOSED SECTIONS: Overview, Financial Growth, Market Valuation, Workforce, Acquisitions, Leadership & Eras, Sources',
      checkpointModified: false,
      model: null,
      tokenUsage: null,
      searchesPerformed: 18,
      sourcesCount: 12,
      sectionsBuilt: 7,
      chartsBuilt: 10,
      filesGenerated: 12,
      productsCompared: null,
      dataPointsCollected: 180,
      phaseTiming: { environment: 3, interpret: 2, survey: 12, discover: 15, research: 35, analyze: 8, build: 35, present: 10 },
      contentAnalysis: {
        fleschKincaidGrade: 10.4,
        fleschKincaidLabel: '10th Grade',
        bloomsLevel: 4,
        bloomsLabel: 'Analyze',
        bloomsRange: 'Understand → Analyze',
        totalWords: 3800,
      },
      hoursSaved: {
        researchHours: 17.1,
        totalHoursSaved: 95.1,
        equivalentLabel: '~2.5 weeks full-time',
        productionHours: { 'interactive-dashboard': 78, 'white-paper': 35.8, 'blog-post': 27.5, 'technical-doc': 24.6, presentation: 15.5, 'github-repo': 47 },
      },
      consumptionTime: {
        estimatedMinutes: 39,
        estimatedLabel: '~40 min deep read',
      },
    },
  },
  {
    slug: 'chainsaw-comparison',
    title: 'Gas Chainsaw Comparison',
    subtitle: 'Product Comparison Dashboard',
    query: "I'm looking to buy a gas chainsaw for property maintenance",
    lens: 'product',
    icon: 'Axe',
    accentColor: 'orange',
    createdAt: '2026-02-09T12:00:00Z',
    telemetry: {
      runStartedAt: '2026-02-09T12:00:00Z',
      runCompletedAt: '2026-02-09T14:30:00Z',
      durationMinutes: 150,
      includedSetup: false,
      skillVersion: '3.0',
      userPrompt: "I'm looking to buy a gas chainsaw for property maintenance",
      researchPlan: "PRODUCT TYPE: Gas Chainsaw\nLIFECYCLE: Durable / Investment (5+ years)\nYOUR PROFILE: Homeowner, property maintenance, moderate budget\nPRODUCTS: 18 models across 6 brands\nTIERS: Entry/Homeowner, Farm & Ranch, Professional\nKEY SPECS: Displacement, HP, weight, bar length, noise, vibration, crankcase\nDERIVED METRICS: Power-to-weight ratio, Price per HP\nFLAGS: Ecosystem ✗, Multi-Use ✓, Features Matrix ✓, TCO ✓\nPROPOSED SECTIONS: Overview, Head-to-Head, Power & Weight, Value Analysis, Features Matrix, Use Case Fit, Recommendations, Sources",
      checkpointModified: false,
      model: null,
      tokenUsage: null,
      searchesPerformed: 24,
      sourcesCount: 18,
      sectionsBuilt: 8,
      chartsBuilt: 14,
      filesGenerated: 14,
      productsCompared: 18,
      dataPointsCollected: 324,
      phaseTiming: { environment: 1, interpret: 3, survey: 15, discover: 20, research: 50, analyze: 10, build: 40, present: 11 },
      contentAnalysis: {
        fleschKincaidGrade: 9.1,
        fleschKincaidLabel: '9th Grade',
        bloomsLevel: 5,
        bloomsLabel: 'Evaluate',
        bloomsRange: 'Understand → Evaluate',
        totalWords: 5200,
      },
      hoursSaved: {
        researchHours: 26,
        totalHoursSaved: 123,
        equivalentLabel: '~3 weeks full-time',
        productionHours: { 'interactive-dashboard': 97, 'white-paper': 44.2, 'blog-post': 34, 'technical-doc': 29.4, presentation: 19, 'github-repo': 59 },
      },
      consumptionTime: {
        estimatedMinutes: 54,
        estimatedLabel: '~55 min deep read',
      },
    },
  },
  {
    slug: 'limelight-history',
    title: 'Limelight Networks History',
    subtitle: 'Rise & Fall of a CDN Pioneer',
    query: 'Research the history of Limelight Networks the CDN',
    lens: 'standard',
    icon: 'Globe',
    accentColor: 'cyan',
    createdAt: '2026-02-10T05:53:00Z',
    telemetry: {
      runStartedAt: '2026-02-10T05:53:00Z',
      runCompletedAt: '2026-02-10T06:30:00Z',
      durationMinutes: 37,
      includedSetup: false,
      skillVersion: '4.0',
      userPrompt: 'Research the history of Limelight Networks the CDN',
      researchPlan: 'TOPIC: Rise & Fall of Limelight Networks (2001-2025)\nTIME AXIS: Technology Eras — 6 periods\nPOPULATIONS: Limelight/Edgio, CDN competitors, CDN industry\nCORE METRICS: Revenue, stock price, market share, network scale\nTAXONOMIES: Eras (6), acquisitions (7), legal events (13)\nPROPOSED SECTIONS: Overview, Financial Journey, Competitive Landscape, Events Timeline, Patent Wars, Acquisitions, The Collapse, Sources',
      checkpointModified: false,
      model: null,
      tokenUsage: null,
      searchesPerformed: 14,
      sourcesCount: 15,
      sectionsBuilt: 8,
      chartsBuilt: 8,
      filesGenerated: 11,
      productsCompared: null,
      dataPointsCollected: 220,
      phaseTiming: { environment: 0, interpret: 2, survey: 10, discover: 8, research: 25, analyze: 5, build: 30, present: 5 },
      contentAnalysis: {
        fleschKincaidGrade: 10.8,
        fleschKincaidLabel: '11th Grade',
        bloomsLevel: 4,
        bloomsLabel: 'Analyze',
        bloomsRange: 'Understand → Analyze',
        totalWords: 4200,
      },
      hoursSaved: {
        researchHours: 18.5,
        totalHoursSaved: 98,
        equivalentLabel: '~2.5 weeks full-time',
        productionHours: { 'interactive-dashboard': 80, 'white-paper': 37, 'blog-post': 28, 'technical-doc': 25, presentation: 16, 'github-repo': 48 },
      },
      consumptionTime: {
        estimatedMinutes: 42,
        estimatedLabel: '~42 min deep read',
      },
    },
  },
  {
    slug: 'generator-comparison',
    title: 'Generator Comparison',
    subtitle: 'Tri-Fuel & Dual-Fuel Home Backup',
    query: 'Research generators for home backup — tri-fuel with natural gas support, 3,300W to 15,000W range',
    lens: 'product',
    icon: 'Zap',
    accentColor: 'amber',
    createdAt: '2026-02-10T06:16:00Z',
    telemetry: {
      runStartedAt: '2026-02-10T06:16:00Z',
      runCompletedAt: '2026-02-10T06:50:00Z',
      durationMinutes: 34,
      includedSetup: false,
      skillVersion: '4.0',
      userPrompt: 'Research a generator for me. I want to eventually run natural gas to it but for now I will probably use gasoline. 3300w minimum up to ~15000w for whole home transfer switch. Gas furnace blower 650W, 3 refrigerators, 3 computers (1 gaming), networking gear, TVs. Summer: AC unit in Hendersonville TN.',
      researchPlan: 'PRODUCT TYPE: Tri-Fuel Portable Generator\nLIFECYCLE: Durable / Investment (5+ years)\nYOUR PROFILE: Homeowner, Hendersonville TN, gas furnace, 3 fridges, gaming PC, wants NG eventually, 3-ton AC in summer\nPRODUCTS: 12 models across 6 brands\nTIERS: Budget, Mid-Range, Whole-Home, Inverter\nKEY SPECS: Running watts (gas/NG/propane), engine cc, weight, noise, THD, runtime, fuel tank\nDERIVED METRICS: Watts-per-dollar (NG), NG-to-Gas ratio, Power-to-weight\nFLAGS: Ecosystem ✗, Multi-Use ✓, Features Matrix ✓, TCO ✓\nPROPOSED SECTIONS: Overview, Head-to-Head, Power Analysis, Value & Cost, Features Matrix, Recommendations, Sources',
      checkpointModified: false,
      model: null,
      tokenUsage: null,
      searchesPerformed: 16,
      sourcesCount: 14,
      sectionsBuilt: 7,
      chartsBuilt: 12,
      filesGenerated: 12,
      productsCompared: 12,
      dataPointsCollected: 288,
      phaseTiming: { environment: 0, interpret: 2, survey: 8, discover: 10, research: 30, analyze: 5, build: 25, present: 5 },
      contentAnalysis: {
        fleschKincaidGrade: 9.5,
        fleschKincaidLabel: '10th Grade',
        bloomsLevel: 5,
        bloomsLabel: 'Evaluate',
        bloomsRange: 'Understand → Evaluate',
        totalWords: 6200,
      },
      hoursSaved: {
        researchHours: 28,
        totalHoursSaved: 130,
        equivalentLabel: '~3.5 weeks full-time',
        productionHours: { 'interactive-dashboard': 102, 'white-paper': 46, 'blog-post': 36, 'technical-doc': 30, presentation: 20, 'github-repo': 62 },
      },
      consumptionTime: {
        estimatedMinutes: 58,
        estimatedLabel: '~1 hr deep read',
      },
    },
  },
];

export const projectComponents = {
  'cisco-history-dashboard': lazy(() => import('./cisco-history-dashboard/App')),
  'chainsaw-comparison': lazy(() => import('./chainsaw-comparison/App')),
  'limelight-history': lazy(() => import('./limelight-history/App')),
  'generator-comparison': lazy(() => import('./generator-comparison/App')),
};
