import { lazy } from 'react';

export const projectRegistry = [
  {
    slug: 'cisco-history-dashboard',
    title: 'Cisco History Dashboard',
    subtitle: '40 Years of Innovation',
    query: 'Research the history of Cisco Systems from founding to present day',
    lens: 'standard',
    icon: 'Building2',
    accentColor: 'cyan',
    visibility: 'public',
    createdAt: '2026-02-08T12:00:00Z',
    telemetry: {
      runStartedAt: '2026-02-08T12:00:00Z',
      runCompletedAt: '2026-02-08T14:00:00Z',
      durationMinutes: 120,
      includedSetup: true,
      skillVersion: '3.0',
      userPrompt: 'Research the history of Cisco Systems from founding to present day',
      researchPlan: 'TOPIC: Cisco Systems Corporate History\nTIME AXIS: Decades — 1984-2026\nPOPULATIONS: Cisco as corporation, leadership eras, acquired companies\nCORE METRICS: Revenue, market cap, employee count, acquisitions\nTAXONOMIES: CEO eras (5), major acquisitions (20+), product lines\nPROPOSED SECTIONS: Overview, Financial Growth, Market Valuation, Workforce, Acquisitions, Leadership & Eras, Sources',
      checkpointModified: false,
      model: null,
      tokenUsage: null,
      searchesPerformed: 18,
      sourcesCount: 12,
      sectionsBuilt: 7,
      chartsBuilt: 10,
      filesGenerated: 12,
      productsCompared: null,
      dataPointsCollected: 180,
      phaseTiming: { environment: 3, interpret: 2, survey: 12, discover: 15, research: 35, analyze: 8, build: 35, present: 10 },
      contentAnalysis: {
        fleschKincaidGrade: 10.4,
        fleschKincaidLabel: '10th Grade',
        bloomsLevel: 4,
        bloomsLabel: 'Analyze',
        bloomsRange: 'Understand → Analyze',
        totalWords: 3800,
      },
      hoursSaved: {
        researchHours: 17.1,
        totalHoursSaved: 95.1,
        equivalentLabel: '~2.5 weeks full-time',
        productionHours: { 'interactive-dashboard': 78, 'white-paper': 35.8, 'blog-post': 27.5, 'technical-doc': 24.6, presentation: 15.5, 'github-repo': 47 },
      },
      consumptionTime: {
        estimatedMinutes: 39,
        estimatedLabel: '~40 min deep read',
      },
      promptComplexity: { wordCount: 12, entityCount: 1, ambiguityScore: 0.3 },
      sourceDiversityScore: 0.67,
      dataQualityDistribution: { t1: 15, t2: 85, t3: 55, t4: 25 },
    },
  },
  {
    slug: 'chainsaw-comparison',
    title: 'Gas Chainsaw Comparison',
    subtitle: 'Product Comparison Dashboard',
    query: "I'm looking to buy a gas chainsaw for property maintenance",
    lens: 'product',
    icon: 'Axe',
    accentColor: 'orange',
    visibility: 'public',
    createdAt: '2026-02-09T12:00:00Z',
    telemetry: {
      runStartedAt: '2026-02-09T12:00:00Z',
      runCompletedAt: '2026-02-09T14:30:00Z',
      durationMinutes: 150,
      includedSetup: false,
      skillVersion: '3.0',
      userPrompt: "I'm looking to buy a gas chainsaw for property maintenance",
      researchPlan: "PRODUCT TYPE: Gas Chainsaw\nLIFECYCLE: Durable / Investment (5+ years)\nYOUR PROFILE: Homeowner, property maintenance, moderate budget\nPRODUCTS: 18 models across 6 brands\nTIERS: Entry/Homeowner, Farm & Ranch, Professional\nKEY SPECS: Displacement, HP, weight, bar length, noise, vibration, crankcase\nDERIVED METRICS: Power-to-weight ratio, Price per HP\nFLAGS: Ecosystem ✗, Multi-Use ✓, Features Matrix ✓, TCO ✓\nPROPOSED SECTIONS: Overview, Head-to-Head, Power & Weight, Value Analysis, Features Matrix, Use Case Fit, Recommendations, Sources",
      checkpointModified: false,
      model: null,
      tokenUsage: null,
      searchesPerformed: 24,
      sourcesCount: 18,
      sectionsBuilt: 8,
      chartsBuilt: 14,
      filesGenerated: 14,
      productsCompared: 18,
      dataPointsCollected: 324,
      phaseTiming: { environment: 1, interpret: 3, survey: 15, discover: 20, research: 50, analyze: 10, build: 40, present: 11 },
      contentAnalysis: {
        fleschKincaidGrade: 9.1,
        fleschKincaidLabel: '9th Grade',
        bloomsLevel: 5,
        bloomsLabel: 'Evaluate',
        bloomsRange: 'Understand → Evaluate',
        totalWords: 5200,
      },
      hoursSaved: {
        researchHours: 26,
        totalHoursSaved: 123,
        equivalentLabel: '~3 weeks full-time',
        productionHours: { 'interactive-dashboard': 97, 'white-paper': 44.2, 'blog-post': 34, 'technical-doc': 29.4, presentation: 19, 'github-repo': 59 },
      },
      consumptionTime: {
        estimatedMinutes: 54,
        estimatedLabel: '~55 min deep read',
      },
      promptComplexity: { wordCount: 11, entityCount: 0, ambiguityScore: 0.6 },
      sourceDiversityScore: 0.56,
      dataQualityDistribution: { t1: 20, t2: 120, t3: 130, t4: 54 },
    },
  },
  {
    slug: 'limelight-history',
    title: 'Limelight Networks History',
    subtitle: 'Rise & Fall of a CDN Pioneer',
    query: 'Research the history of Limelight Networks the CDN',
    lens: 'standard',
    icon: 'Globe',
    accentColor: 'cyan',
    visibility: 'public',
    createdAt: '2026-02-10T05:53:00Z',
    telemetry: {
      runStartedAt: '2026-02-10T05:53:00Z',
      runCompletedAt: '2026-02-10T06:30:00Z',
      durationMinutes: 37,
      includedSetup: false,
      skillVersion: '4.0',
      userPrompt: 'Research the history of Limelight Networks the CDN',
      researchPlan: 'TOPIC: Rise & Fall of Limelight Networks (2001-2025)\nTIME AXIS: Technology Eras — 6 periods\nPOPULATIONS: Limelight/Edgio, CDN competitors, CDN industry\nCORE METRICS: Revenue, stock price, market share, network scale\nTAXONOMIES: Eras (6), acquisitions (7), legal events (13)\nPROPOSED SECTIONS: Overview, Financial Journey, Competitive Landscape, Events Timeline, Patent Wars, Acquisitions, The Collapse, Sources',
      checkpointModified: false,
      model: null,
      tokenUsage: null,
      searchesPerformed: 14,
      sourcesCount: 15,
      sectionsBuilt: 8,
      chartsBuilt: 8,
      filesGenerated: 11,
      productsCompared: null,
      dataPointsCollected: 220,
      phaseTiming: { environment: 0, interpret: 2, survey: 10, discover: 8, research: 25, analyze: 5, build: 30, present: 5 },
      contentAnalysis: {
        fleschKincaidGrade: 10.8,
        fleschKincaidLabel: '11th Grade',
        bloomsLevel: 4,
        bloomsLabel: 'Analyze',
        bloomsRange: 'Understand → Analyze',
        totalWords: 4200,
      },
      hoursSaved: {
        researchHours: 18.5,
        totalHoursSaved: 98,
        equivalentLabel: '~2.5 weeks full-time',
        productionHours: { 'interactive-dashboard': 80, 'white-paper': 37, 'blog-post': 28, 'technical-doc': 25, presentation: 16, 'github-repo': 48 },
      },
      consumptionTime: {
        estimatedMinutes: 42,
        estimatedLabel: '~42 min deep read',
      },
      promptComplexity: { wordCount: 9, entityCount: 1, ambiguityScore: 0.2 },
      sourceDiversityScore: 0.67,
      dataQualityDistribution: { t1: 25, t2: 95, t3: 70, t4: 30 },
    },
  },
  {
    slug: 'generator-comparison',
    title: 'Generator Comparison',
    subtitle: 'Tri-Fuel & Dual-Fuel Home Backup',
    query: 'Research generators for home backup — tri-fuel with natural gas support, 3,300W to 15,000W range',
    lens: 'product',
    icon: 'Zap',
    accentColor: 'amber',
    visibility: 'public',
    createdAt: '2026-02-10T06:16:00Z',
    telemetry: {
      runStartedAt: '2026-02-10T06:16:00Z',
      runCompletedAt: '2026-02-10T06:50:00Z',
      durationMinutes: 34,
      includedSetup: false,
      skillVersion: '4.0',
      userPrompt: 'Research a generator for me. I want to eventually run natural gas to it but for now I will probably use gasoline. 3300w minimum up to ~15000w for whole home transfer switch. Gas furnace blower 650W, 3 refrigerators, 3 computers (1 gaming), networking gear, TVs. Summer: AC unit in Hendersonville TN.',
      researchPlan: 'PRODUCT TYPE: Tri-Fuel Portable Generator\nLIFECYCLE: Durable / Investment (5+ years)\nYOUR PROFILE: Homeowner, Hendersonville TN, gas furnace, 3 fridges, gaming PC, wants NG eventually, 3-ton AC in summer\nPRODUCTS: 12 models across 6 brands\nTIERS: Budget, Mid-Range, Whole-Home, Inverter\nKEY SPECS: Running watts (gas/NG/propane), engine cc, weight, noise, THD, runtime, fuel tank\nDERIVED METRICS: Watts-per-dollar (NG), NG-to-Gas ratio, Power-to-weight\nFLAGS: Ecosystem ✗, Multi-Use ✓, Features Matrix ✓, TCO ✓\nPROPOSED SECTIONS: Overview, Head-to-Head, Power Analysis, Value & Cost, Features Matrix, Recommendations, Sources',
      checkpointModified: false,
      model: null,
      tokenUsage: null,
      searchesPerformed: 16,
      sourcesCount: 14,
      sectionsBuilt: 7,
      chartsBuilt: 12,
      filesGenerated: 12,
      productsCompared: 12,
      dataPointsCollected: 288,
      phaseTiming: { environment: 0, interpret: 2, survey: 8, discover: 10, research: 30, analyze: 5, build: 25, present: 5 },
      contentAnalysis: {
        fleschKincaidGrade: 9.5,
        fleschKincaidLabel: '10th Grade',
        bloomsLevel: 5,
        bloomsLabel: 'Evaluate',
        bloomsRange: 'Understand → Evaluate',
        totalWords: 6200,
      },
      hoursSaved: {
        researchHours: 28,
        totalHoursSaved: 130,
        equivalentLabel: '~3.5 weeks full-time',
        productionHours: { 'interactive-dashboard': 102, 'white-paper': 46, 'blog-post': 36, 'technical-doc': 30, presentation: 20, 'github-repo': 62 },
      },
      consumptionTime: {
        estimatedMinutes: 58,
        estimatedLabel: '~1 hr deep read',
      },
      promptComplexity: { wordCount: 50, entityCount: 6, ambiguityScore: 0.2 },
      sourceDiversityScore: 0.64,
      dataQualityDistribution: { t1: 25, t2: 110, t3: 105, t4: 48 },
    },
  },
  {
    slug: 'homeschool-curriculum',
    title: 'Homeschool Curriculum Guide',
    subtitle: 'Curricula & Co-op Programs for Advanced Learners',
    query: 'Research homeschool curricula and co-op programs near Hendersonville TN (37075) for an advanced child',
    lens: 'standard',
    icon: 'GraduationCap',
    accentColor: 'violet',
    visibility: 'public',
    createdAt: '2026-02-10T09:06:00Z',
    telemetry: {
      runStartedAt: '2026-02-10T09:06:00Z',
      runCompletedAt: '2026-02-10T09:50:00Z',
      durationMinutes: 44,
      includedSetup: false,
      skillVersion: '4.0',
      userPrompt: 'Research homeschool curricula for an advanced child moving from Three Oaks Academy to a choose-your-own-curriculum co-op model. Also research co-op programs near 37075 including CHET and Anchored at Long Hollow Church.',
      researchPlan: 'TOPIC: Homeschool Curriculum & Co-op Guide\nFOCUS: Advanced learner, grade acceleration, parent-chosen curriculum\nPOPULATIONS: 13 curricula, 7 co-op programs near 37075\nCORE METRICS: Cost, advanced-friendliness, self-pacing, parent involvement, grade range\nPROPOSED SECTIONS: Overview, Curriculum Comparison, Cost Analysis, Co-op Programs, CHET vs Anchored, Recommendations, Sources',
      checkpointModified: false,
      model: null,
      tokenUsage: null,
      searchesPerformed: 20,
      sourcesCount: 31,
      sectionsBuilt: 7,
      chartsBuilt: 3,
      filesGenerated: 10,
      productsCompared: null,
      dataPointsCollected: 260,
      phaseTiming: { environment: 1, interpret: 2, survey: 10, discover: 8, research: 15, analyze: 3, build: 20, present: 5 },
      contentAnalysis: {
        fleschKincaidGrade: 9.2,
        fleschKincaidLabel: '9th Grade',
        bloomsLevel: 5,
        bloomsLabel: 'Evaluate',
        bloomsRange: 'Understand → Evaluate',
        totalWords: 5800,
      },
      hoursSaved: {
        researchHours: 28.5,
        totalHoursSaved: 99.5,
        equivalentLabel: '~2.5 weeks full-time',
        productionHours: { 'interactive-dashboard': 71, 'white-paper': 40.9, 'blog-post': 20.5, 'technical-doc': 30.3, presentation: 12, 'github-repo': 46 },
      },
      consumptionTime: {
        estimatedMinutes: 48,
        estimatedLabel: '~50 min deep read',
      },
      promptComplexity: { wordCount: 30, entityCount: 5, ambiguityScore: 0.3 },
      sourceDiversityScore: 0.65,
      dataQualityDistribution: { t1: 10, t2: 80, t3: 120, t4: 50 },
    },
  },
  {
    slug: 'pixel-upgrade-analysis-mrshaun13',
    title: 'Pixel 9 Pro Upgrade Analysis',
    subtitle: 'Should you upgrade? Tick-tock innovation cycles, cost analysis & verdict',
    query: 'Is it worth upgrading from the Pixel 9 Pro to a new Pixel phone right now?',
    lens: 'product',
    icon: 'Smartphone',
    accentColor: 'emerald',
    visibility: 'public',
    createdAt: '2026-02-10T18:23:00Z',
    telemetry: {
      runStartedAt: '2026-02-10T18:00:00Z',
      runCompletedAt: '2026-02-10T19:09:00Z',
      durationMinutes: 44,
      includedSetup: true,
      skillVersion: '5.1',
      userPrompt: 'I want to do research about if it is worth upgrading from the pixel 9 pro to a new pixel phone right now.',
      researchPlan: 'PRODUCT TYPE: Google Pixel Smartphone (Upgrade Analysis)\nPHONES COMPARED: 6 models (Pixel 6 Pro through 10 Pro)\nSECTIONS: Overview, Spec Comparison, Feature Delta, Innovation Cycles, Upgrade Cost, Pros & Cons, Recommendations, Sources',
      checkpointModified: true,
      model: null,
      tokenUsage: null,
      searchesPerformed: 8,
      sourcesCount: 12,
      sectionsBuilt: 8,
      chartsBuilt: 4,
      filesGenerated: 12,
      productsCompared: 6,
      dataPointsCollected: 264,
      phaseTiming: { environment: 15, interpret: 3, survey: 5, discover: 8, research: 10, analyze: 2, build: 20, present: 6 },
      contentAnalysis: {
        fleschKincaidGrade: 10.1,
        fleschKincaidLabel: '10th Grade',
        bloomsLevel: 5,
        bloomsLabel: 'Evaluate',
        bloomsRange: 'Understand → Evaluate',
        totalWords: 4500,
        totalSentences: 225,
        readabilityNote: 'Consumer-friendly product analysis with data-driven recommendations and decision frameworks',
      },
      hoursSaved: {
        researchHours: 16.3,
        totalHoursSaved: 82,
        equivalentLabel: '~2 weeks full-time',
        productionHours: { 'interactive-dashboard': 66, 'white-paper': 40.6, 'blog-post': 24, 'technical-doc': 27.6, presentation: 14, 'github-repo': 38 },
      },
      consumptionTime: {
        estimatedMinutes: 37,
        readingMinutes: 22.5,
        chartExplorationMinutes: 10,
        interactiveOverheadMinutes: 4,
        estimatedLabel: '~35 min deep read',
      },
      promptComplexity: { wordCount: 22, entityCount: 1, ambiguityScore: 0.4 },
      sourceDiversityScore: 0.58,
      dataQualityDistribution: { t1: 30, t2: 100, t3: 95, t4: 39 },
    },
  },
  {
    slug: 'ai-tooling-adoption-mrshaun13',
    title: 'AI Developer Tooling Adoption',
    subtitle: 'Hype vs Reality — Agents, MCP, Skills & the Adoption Paradox',
    query: 'Research the adoption rate of modern AI developer tooling — agents, MCP servers, skills/workflows, AGENTS.md. Is it really on a huge climb or still slow? Include future projections.',
    lens: 'standard',
    icon: 'Brain',
    accentColor: 'cyan',
    visibility: 'public',
    createdAt: '2026-02-10T22:49:00Z',
    telemetry: {
      runStartedAt: '2026-02-10T22:00:00Z',
      runCompletedAt: '2026-02-10T23:15:00Z',
      durationMinutes: 75,
      includedSetup: false,
      skillVersion: '5.1',
      userPrompt: 'I want to research the adoption rate of the more modern AI tooling that exists that are considered the game changing ways of using an AI agent. agents.md, skills.md, MCP servers. Is it really on a huge climb or is it still really slow? Include future projections.',
      researchPlan: 'TOPIC: Adoption Rate of Modern AI Developer Tooling — Hype vs Reality\nTIME AXIS: Technology Eras (Pre-Copilot, Copilot Era, Chat-Augmented, Agentic Explosion)\nCATEGORIES: AI Coding Assistants, Agentic Coding, MCP Servers, Agent Instruction Files, Skills & Workflows\nCORE METRICS: User growth, revenue, developer survey adoption, GitHub stars, enterprise adoption, sentiment/trust, productivity impact, market projections\nHYPE VS REALITY: Scorecard with gap analysis\nPROPOSED SECTIONS: Overview, Growth Timelines, Reality Check, Tool Deep Dive, Enterprise vs Individual, Future Projections, Sources',
      checkpointModified: false,
      model: null,
      tokenUsage: null,
      searchesPerformed: 12,
      sourcesCount: 15,
      sectionsBuilt: 7,
      chartsBuilt: 12,
      filesGenerated: 11,
      productsCompared: null,
      dataPointsCollected: 300,
      phaseTiming: { environment: 2, interpret: 3, survey: 10, discover: 10, research: 15, analyze: 5, build: 25, present: 5 },
      contentAnalysis: {
        fleschKincaidGrade: 10.5,
        fleschKincaidLabel: '11th Grade',
        bloomsLevel: 5,
        bloomsLabel: 'Evaluate',
        bloomsRange: 'Understand → Evaluate',
        totalWords: 7377,
        totalSentences: 369,
        readabilityNote: 'Data-driven analysis with hype-vs-reality framework and multi-dimensional adoption metrics',
      },
      hoursSaved: {
        researchHours: 20.25,
        totalHoursSaved: 103.75,
        equivalentLabel: '~2.5 weeks full-time',
        productionHours: { 'interactive-dashboard': 83.5, 'white-paper': 43.5, 'blog-post': 29.5, 'technical-doc': 25.5, presentation: 16.5, 'github-repo': 51.5 },
      },
      consumptionTime: {
        estimatedMinutes: 70,
        readingMinutes: 49.2,
        chartExplorationMinutes: 9,
        interactiveOverheadMinutes: 11.6,
        estimatedLabel: '~1 hr deep read',
      },
      promptComplexity: { wordCount: 40, entityCount: 4, ambiguityScore: 0.4 },
      sourceDiversityScore: 0.80,
      dataQualityDistribution: { t1: 20, t2: 110, t3: 120, t4: 50 },
    },
  },
  {
    slug: 'coffee-beans-deep-dive-djagger',
    title: 'Coffee Beans Deep Dive',
    subtitle: 'Species, varieties, caffeine, flavor, rarity & global production',
    query: 'Research the different types of coffee beans — quality, flavor, caffeine, which keep you awake most, international varieties, rare beans',
    lens: 'standard',
    icon: 'Coffee',
    accentColor: 'amber',
    visibility: 'public',
    createdAt: '2026-02-10T22:57:00Z',
    telemetry: {
      runStartedAt: '2026-02-10T22:57:00Z',
      runCompletedAt: '2026-02-10T23:15:00Z',
      durationMinutes: 18,
      includedSetup: true,
      skillVersion: '6.0',
      userPrompt: 'Research the different types of coffee beans and which ones are highest quality, rating flavor and caffeine amount, which ones keep you awake the most vs which ones don\'t. Do a deep dive into coffee beans all types of them, internationally, easy to get, rare, etc.',
      researchPlan: 'TOPIC: Coffee Beans — Global Taxonomy & Comparison\nTIME AXIS: Not time-dependent (taxonomic study)\nPOPULATIONS: 4 species, 15 Arabica varieties, 10 rare coffees, 10 producing countries\nCORE METRICS: Caffeine content, flavor rating, cupping score, price, production volume\nTAXONOMIES: Species (4), Arabica varieties (15), rare coffees (10), processing methods (5)\nPROPOSED SECTIONS: Overview, Caffeine & Alertness, Flavor Profiles, Arabica Varieties, Rare & Expensive, Global Production, Processing Methods, Sources',
      checkpointModified: false,
      model: 'claude-sonnet',
      tokenUsage: null,
      searchesPerformed: 8,
      sourcesCount: 12,
      sectionsBuilt: 8,
      chartsBuilt: 12,
      filesGenerated: 11,
      productsCompared: null,
      dataPointsCollected: 285,
      phaseTiming: { environment: 5, interpret: 1, survey: 3, discover: 2, research: 3, analyze: 1, build: 8, present: 2 },
      contentAnalysis: {
        fleschKincaidGrade: 10,
        fleschKincaidLabel: '10th Grade',
        bloomsLevel: 4,
        bloomsLabel: 'Analyze',
        bloomsRange: 'Understand → Analyze',
        totalWords: 4800,
      },
      hoursSaved: {
        researchHours: 14,
        totalHoursSaved: 78,
        equivalentLabel: '~2 weeks full-time',
        productionHours: { 'interactive-dashboard': 62, 'white-paper': 32, 'blog-post': 22, 'technical-doc': 20, presentation: 12, 'github-repo': 40 },
      },
      consumptionTime: {
        estimatedMinutes: 25,
        estimatedLabel: '~25 min deep read',
      },
      promptComplexity: { wordCount: 40, entityCount: 0, ambiguityScore: 0.5 },
      sourceDiversityScore: 0.75,
      dataQualityDistribution: { t1: 30, t2: 120, t3: 100, t4: 35 },
    },
  },
  {
    slug: 'solar-system-explorer-mrshaun13',
    title: 'Solar System Explorer',
    subtitle: 'An Interactive Space Adventure for Kids — All 8 Planets + Pluto!',
    query: 'Build a cool learning experience for a seven-year-old advanced first grader to learn about our solar system with the ability to zoom in to all the planets and see every stat about their size and everything.',
    lens: 'standard',
    icon: 'Globe',
    accentColor: 'blue',
    visibility: 'public',
    createdAt: '2026-02-11T03:48:00Z',
    telemetry: {
      runStartedAt: '2026-02-11T03:46:00Z',
      runCompletedAt: '2026-02-11T16:45:00Z',
      durationMinutes: 180,
      includedSetup: false,
      skillVersion: '6.1',
      userPrompt: 'Build a cool learning experience for a seven-year-old advanced first grader to learn about our solar system with the ability to zoom in to all the planets and see every stat about their size and everything. Add a funny dad joke per planet too.',
      researchPlan: 'TOPIC: Our Solar System — An Interactive Space Explorer for Kids\nAUDIENCE: 7-year-old advanced first grader\nPLANETS: All 8 + Sun + Pluto\nGROUPING: Inner Rocky vs Outer Giants\nKEY STATS: Distance, diameter, day/year length, gravity, temperature, moons, atmosphere, fun facts, dad jokes, exploration history\nSECTIONS: Mission Control, Planet Explorer, Space Records (7 sub-tabs), Size Showdown, Hot & Cold, Gravity Playground, Race to the Sun, Earth Moon & Seasons, Night Sky, Space Events, Space Timeline, Trivia Game, Space Lab, Space Library\nINTERACTIVES: Wind Race Game, Time Converter, Spinning Planet Comparator, Gravity Calculator, Distance Race, Constellation Viewer, Trivia Game',
      checkpointModified: true,
      model: null,
      tokenUsage: null,
      searchesPerformed: 5,
      sourcesCount: 8,
      sectionsBuilt: 14,
      chartsBuilt: 22,
      filesGenerated: 23,
      productsCompared: null,
      dataPointsCollected: 620,
      phaseTiming: { environment: 1, interpret: 1, survey: 2, discover: 1, research: 2, analyze: 1, build: 160, present: 12 },
      contentAnalysis: {
        fleschKincaidGrade: 3.5,
        fleschKincaidLabel: '3rd–4th Grade',
        bloomsLevel: 3,
        bloomsLabel: 'Apply',
        bloomsRange: 'Remember → Apply',
        totalWords: 9200,
        totalSentences: 780,
        readabilityNote: 'Kid-friendly space exploration with interactive games, animated comparisons, real-world analogies, and hands-on learning for a 7-year-old audience. Includes wind speed race game, planet time converter, spinning planet comparator, and rich record book.',
      },
      hoursSaved: {
        researchHours: 12,
        totalHoursSaved: 98,
        equivalentLabel: '~2.5 weeks full-time',
        productionHours: { 'interactive-dashboard': 86, 'white-paper': 38, 'blog-post': 26, 'technical-doc': 28, presentation: 16, 'github-repo': 52 },
      },
      consumptionTime: {
        estimatedMinutes: 75,
        readingMinutes: 36,
        chartExplorationMinutes: 16.5,
        interactiveOverheadMinutes: 22.5,
        estimatedLabel: '~75 min fun exploration',
      },
      promptComplexity: { wordCount: 35, entityCount: 0, ambiguityScore: 0.4 },
      sourceDiversityScore: 0.75,
      dataQualityDistribution: { t1: 280, t2: 200, t3: 100, t4: 40 },
    },
  },
  {
    slug: 'traitors-s3-analytics-mrshaun13',
    title: 'The Traitors S3 Analytics',
    subtitle: 'Spoiler-Free Game Intelligence Dashboard — Season 3 (US)',
    query: 'Build an interactive analytics dashboard for The Traitors Season 3 (US) with episode-gated spoiler protection, player profiles, social game scores, deception tracking, alliance maps, and game statistics.',
    lens: 'standard',
    icon: 'Flame',
    accentColor: 'red',
    visibility: 'personal',
    createdAt: '2026-02-11T19:48:00Z',
    telemetry: {
      runStartedAt: '2026-02-11T19:48:00Z',
      runCompletedAt: '2026-02-12T01:30:00Z',
      durationMinutes: 102,
      includedSetup: false,
      skillVersion: '6.2',
      userPrompt: 'Build an interactive analytics dashboard for The Traitors Season 3 with episode-gated spoiler protection, player breakdowns, social game scores, deception tracking, and game statistics.',
      researchPlan: 'TOPIC: The Traitors US Season 3 Game Analytics\nSOURCES: Wikipedia, Peacock Official Recaps (Ep 1-11), NBC Insider, Fandom Wiki\nPLAYERS: 23 contestants with full stats\nEPISODES: 11 game episodes + reunion\nMETRICS: Social game score, vote accuracy, shields, deceptions, alliances, eliminations\nSPOILER SYSTEM: Episode gate (1-11) hides future events\nSECTIONS: Overview, Players, Timeline, Deception, Alliances',
      checkpointModified: false,
      model: null,
      tokenUsage: null,
      searchesPerformed: 12,
      sourcesCount: 15,
      sectionsBuilt: 5,
      chartsBuilt: 7,
      filesGenerated: 8,
      productsCompared: null,
      dataPointsCollected: 450,
      phaseTiming: { environment: 1, interpret: 2, survey: 5, discover: 15, research: 30, analyze: 10, build: 30, present: 9 },
      contentAnalysis: {
        fleschKincaidGrade: 8.5,
        fleschKincaidLabel: '8th-9th Grade',
        bloomsLevel: 4,
        bloomsLabel: 'Analyze',
        bloomsRange: 'Understand → Analyze',
        totalWords: 8500,
        totalSentences: 425,
        readabilityNote: 'Interactive game analytics with spoiler-gated episode progression, player profiles, deception tracking, and social game scoring',
      },
      hoursSaved: {
        researchHours: 22,
        totalHoursSaved: 110,
        equivalentLabel: '~3 weeks full-time',
        productionHours: { 'interactive-dashboard': 88, 'white-paper': 44, 'blog-post': 30, 'technical-doc': 26, presentation: 16, 'github-repo': 54 },
      },
      consumptionTime: {
        estimatedMinutes: 90,
        readingMinutes: 40,
        chartExplorationMinutes: 25,
        interactiveOverheadMinutes: 25,
        estimatedLabel: '~90 min deep exploration',
      },
      promptComplexity: { wordCount: 25, entityCount: 2, ambiguityScore: 0.2 },
      sourceDiversityScore: 0.53,
      dataQualityDistribution: { t1: 50, t2: 150, t3: 180, t4: 70 },
    },
  },
  {
    slug: 'skill-showcase-mrshaun13',
    title: 'Research Visualizer Showcase',
    subtitle: 'How This Skill Works — Pipeline, Scaffold, Telemetry & Hub Architecture',
    query: 'Build a showcase of the research-visualizer skill itself, demonstrating the diversity of projects it produces, its 8-phase pipeline, scaffold layer, telemetry system, and centralized research hub with public sharing.',
    lens: 'standard',
    icon: 'Sparkles',
    accentColor: 'violet',
    visibility: 'personal',
    createdAt: '2026-02-12T07:24:00Z',
    telemetry: {
      runStartedAt: '2026-02-12T07:24:00Z',
      runCompletedAt: '2026-02-12T08:30:00Z',
      durationMinutes: 66,
      includedSetup: false,
      skillVersion: '6.3',
      userPrompt: 'Build a showcase of the research-visualizer skill itself, demonstrating the diversity of projects it produces, its 8-phase pipeline, scaffold layer, telemetry system, and centralized research hub with public sharing.',
      researchPlan: 'TOPIC: Research Visualizer Skill Showcase\nTYPE: Meta-project — a research dashboard about the tool that creates research dashboards\nDATA SOURCE: Real telemetry from 5 existing projects\nSECTIONS: Overview, Project Gallery (5 screenshots), The Pipeline (8 phases), Scaffold Layer (config architecture, evolution timeline), Telemetry (formulas, charts, content analysis), Research Hub (contribution flow, GitHub Actions, security model), Sources',
      checkpointModified: false,
      model: null,
      tokenUsage: null,
      searchesPerformed: 6,
      sourcesCount: 6,
      sectionsBuilt: 7,
      chartsBuilt: 4,
      filesGenerated: 10,
      productsCompared: null,
      dataPointsCollected: 150,
      phaseTiming: { environment: 1, interpret: 2, survey: 3, discover: 5, research: 7, analyze: 5, build: 38, present: 5 },
      contentAnalysis: {
        fleschKincaidGrade: 11.5,
        fleschKincaidLabel: '11th-12th Grade',
        bloomsLevel: 4,
        bloomsLabel: 'Analyze',
        bloomsRange: 'Understand → Evaluate',
        totalWords: 5800,
        totalSentences: 290,
        readabilityNote: 'Technical showcase with architecture diagrams, real telemetry visualizations, and pipeline documentation',
      },
      hoursSaved: {
        researchHours: 4.5,
        totalHoursSaved: 51.5,
        equivalentLabel: '~1.5 weeks full-time',
        productionHours: { 'interactive-dashboard': 47, 'white-paper': 31, 'blog-post': 21.5, 'technical-doc': 22.8, presentation: 12.5, 'github-repo': 30 },
      },
      consumptionTime: {
        estimatedMinutes: 50,
        readingMinutes: 38.7,
        chartExplorationMinutes: 3,
        interactiveOverheadMinutes: 8.3,
        estimatedLabel: '~50 min deep read',
      },
      promptComplexity: { wordCount: 30, entityCount: 1, ambiguityScore: 0.3 },
      sourceDiversityScore: 0.67,
      dataQualityDistribution: { t1: 60, t2: 50, t3: 30, t4: 10 },
    },
  },
  {
    slug: 'smart-telescope-finder-mrshaun13',
    title: 'Smart Telescope Finder',
    subtitle: 'Porch Stargazing & Nashville Skyline — 12 Models, 5 Brands, Your Perfect Scope',
    query: 'Find me a telescope or similar device I can sit on my porch and control remotely from my phone with live image cast to my TV. Needs to do stargazing AND terrestrial viewing of the Nashville skyline 1-20 miles away.',
    lens: 'product',
    icon: 'Telescope',
    accentColor: 'cyan',
    visibility: 'public',
    createdAt: '2026-02-13T04:13:00Z',
    contributor: 'mrshaun13',
    telemetry: {
      runStartedAt: '2026-02-13T04:13:00Z',
      runCompletedAt: '2026-02-13T04:50:00Z',
      durationMinutes: 37,
      includedSetup: false,
      skillVersion: '6.3',
      userPrompt: 'I want to find a telescope or similar device that I can sit on my porch and control it remotely and have the image show up live on my phone which I can cast to my TV. It needs to do stargazing but also give me cool visual zooms of buildings and roads 1-20 miles away because I can see the Nashville skyline from my house.',
      researchPlan: 'PRODUCT TYPE: Smart Telescopes & Remote-Viewing Optics\nLIFECYCLE: Durable / Investment (5+ years)\nYOUR PROFILE: Porch-mounted, phone-controlled, live to TV, dual-use (astro + terrestrial Nashville skyline)\nPRODUCTS: 12 models across 5 brands, 3 tiers\nKEY SPECS: Aperture, Focal Length, Sensor Resolution, FOV, Weight, Battery, Storage, Sensor\nDERIVED METRICS: Price per mm aperture, MP per $1K\nFLAGS: Ecosystem ✓, Multi-Use ✓, Features Matrix ✓, Clear Tiers ✓, Derived Metrics ✓\nSECTIONS: Overview, Spec Comparison, Optics Deep Dive, Use Case Fit, Features Matrix, Recommendations, Sources',
      checkpointModified: false,
      model: null,
      tokenUsage: null,
      searchesPerformed: 10,
      sourcesCount: 14,
      sectionsBuilt: 7,
      chartsBuilt: 10,
      filesGenerated: 10,
      productsCompared: 12,
      dataPointsCollected: 480,
      phaseTiming: { environment: 1, interpret: 2, survey: 5, discover: 5, research: 8, analyze: 3, build: 10, present: 3 },
      contentAnalysis: {
        fleschKincaidGrade: 9.8,
        fleschKincaidLabel: '10th Grade',
        bloomsLevel: 5,
        bloomsLabel: 'Evaluate',
        bloomsRange: 'Understand → Evaluate',
        totalWords: 8200,
        totalSentences: 410,
        readabilityNote: 'Consumer-friendly product comparison with data-driven recommendations, interactive charts, and decision frameworks for dual-use smart telescope selection',
      },
      hoursSaved: {
        researchHours: 18.5,
        totalHoursSaved: 92,
        equivalentLabel: '~2.5 weeks full-time',
        productionHours: { 'interactive-dashboard': 73.5, 'white-paper': 42, 'blog-post': 28, 'technical-doc': 26, presentation: 15, 'github-repo': 45 },
      },
      consumptionTime: {
        estimatedMinutes: 45,
        readingMinutes: 27.3,
        chartExplorationMinutes: 10,
        interactiveOverheadMinutes: 7.7,
        estimatedLabel: '~45 min deep exploration',
      },
      promptComplexity: { wordCount: 50, entityCount: 2, ambiguityScore: 0.3 },
      sourceDiversityScore: 0.64,
      dataQualityDistribution: { t1: 40, t2: 180, t3: 190, t4: 70 },
    },
  },
  {
    slug: 'career-pivot-explorer-mrshaun13',
    title: 'Career Pivot Explorer',
    subtitle: 'From EA to What\'s Next — 18 Jobs, 4 Stress Tiers, Your Path Forward',
    query: 'I\'m 50, been an Executive Assistant for 25 years in Hendersonville TN. Help me explore career pivot options from low-stress retail/receptionist jobs to leveraged professional roles like event planning. Show pay ranges, stress levels, and how my skills transfer.',
    lens: 'standard',
    icon: 'Compass',
    accentColor: 'violet',
    visibility: 'public',
    createdAt: '2026-02-11T03:33:00Z',
    contributor: 'mrshaun13',
    telemetry: {
      runStartedAt: '2026-02-11T03:33:00Z',
      runCompletedAt: '2026-02-11T04:15:00Z',
      durationMinutes: 42,
      includedSetup: false,
      skillVersion: '6.1',
      userPrompt: 'I\'m 50 years old in Hendersonville TN, been an EA my whole career. Considering a lifestyle change — exploring options from receptionist at a dentist\'s office or Costco to event planning. Help me explore my options with pay ranges and stress levels.',
      researchPlan: 'TOPIC: Career Pivot Explorer — Hendersonville, TN\nPROFILE: 50yo, 25yr EA veteran, Hendersonville TN\nTIERS: Chill Zone, Comfortable Middle, Leveraged Pivot, Ambitious Stretch\nJOBS: 18 roles across 4 stress tiers\nMETRICS: Salary range, O*NET stress score, take-home drama factor, skill match %, entry barrier, benefits quality\nPROPOSED SECTIONS: Overview, The Spectrum, Tier Breakdown, Head-to-Head, Your Skills, The Money Math, Sources & Next Steps',
      checkpointModified: false,
      model: null,
      tokenUsage: null,
      searchesPerformed: 15,
      sourcesCount: 15,
      sectionsBuilt: 7,
      chartsBuilt: 8,
      filesGenerated: 10,
      productsCompared: null,
      dataPointsCollected: 324,
      phaseTiming: { environment: 1, interpret: 2, survey: 8, discover: 6, research: 8, analyze: 3, build: 10, present: 4 },
      contentAnalysis: {
        fleschKincaidGrade: 9.2,
        fleschKincaidLabel: '9th Grade',
        bloomsLevel: 5,
        bloomsLabel: 'Evaluate',
        bloomsRange: 'Understand → Evaluate',
        totalWords: 6200,
        totalSentences: 310,
        readabilityNote: 'Conversational career guidance with data-driven salary and stress analysis personalized to user profile',
      },
      hoursSaved: {
        researchHours: 18.5,
        totalHoursSaved: 94,
        equivalentLabel: '~2.5 weeks full-time',
        productionHours: { 'interactive-dashboard': 75.5, 'white-paper': 42, 'blog-post': 27, 'technical-doc': 24, presentation: 15, 'github-repo': 46 },
      },
      consumptionTime: {
        estimatedMinutes: 55,
        readingMinutes: 31,
        chartExplorationMinutes: 16,
        interactiveOverheadMinutes: 8,
        estimatedLabel: '~55 min deep read',
      },
    },
  },
  {
    slug: 'skill-architecture-v7-mrshaun13',
    title: 'Research Visualizer v7 Architecture',
    subtitle: 'Complete Architecture Deep Dive — Pipeline, Config, Extensions, Hub & Telemetry',
    query: 'Deep research the research-visualizer skill v7.0 architecture — pipeline flow, config layers, extension system, hub architecture, telemetry, visibility, and community library. Present as a product demo showing both how it works and what the end user experiences.',
    lens: 'standard',
    icon: 'Sparkles',
    accentColor: 'violet',
    visibility: 'public',
    createdAt: '2026-02-13T17:16:00Z',
    contributor: 'mrshaun13',
    telemetry: {
      runStartedAt: '2026-02-13T17:16:00Z',
      runCompletedAt: '2026-02-13T17:42:00Z',
      durationMinutes: 26,
      includedSetup: false,
      skillVersion: '7.0',
      userPrompt: 'Deep research the research-visualizer skill v7.0 architecture — pipeline flow, config layers, extension system, hub architecture, telemetry, visibility, and community library. Present as a product demo showing both how it works and what the end user experiences.',
      researchPlan: 'TOPIC: Research Visualizer Skill v7.0 — Complete Architecture Deep Dive\nTIME AXIS: Current state (v7.0) with version evolution context\nPOPULATIONS: 8 subsystems (Pipeline, Config, Extensions, Hub, Telemetry, Visibility, Library, Collections)\nCORE METRICS: Component count, data flow paths, decision points, file counts, config fields\nSECTIONS: 8 sections',
      checkpointModified: false,
      model: 'claude-sonnet-4-20250514',
      tokenUsage: null,
      searchesPerformed: 2,
      sourcesCount: 10,
      sectionsBuilt: 8,
      chartsBuilt: 9,
      filesGenerated: 12,
      productsCompared: null,
      dataPointsCollected: 186,
      phaseTiming: { environment: 1, interpret: 1, survey: 2, discover: 3, research: 5, analyze: 2, build: 10, present: 2 },
      contentAnalysis: {
        fleschKincaidGrade: 11.4,
        fleschKincaidLabel: '11th Grade',
        bloomsLevel: 4,
        bloomsLabel: 'Analyze',
        bloomsRange: 'Understand → Evaluate',
        totalWords: 5200,
        totalSentences: 260,
        readabilityNote: 'Technical architecture documentation with analytical insight callouts and product demo framing',
      },
      hoursSaved: {
        researchHours: 11.72,
        totalHoursSaved: 92.72,
        equivalentLabel: '~2.5 weeks full-time',
        productionHours: { 'interactive-dashboard': 81, 'white-paper': 38.86, 'blog-post': 29, 'technical-doc': 27, presentation: 16.5, 'github-repo': 48 },
      },
      consumptionTime: {
        estimatedMinutes: 52,
        readingMinutes: 37,
        chartExplorationMinutes: 6.75,
        interactiveOverheadMinutes: 8.75,
        estimatedLabel: '~52 min deep read',
      },
      dataQualityDistribution: { t1: 186, t2: 0, t3: 0, t4: 0 },
      sourceDiversityScore: 0.8,
      promptComplexity: { wordCount: 42, entityCount: 7, ambiguityScore: 0.2 },
    },
  },
  {
    slug: 'az-homeschool-guide-mrshaun13',
    title: 'AZ Homeschool Curriculum & Co-op Guide',
    subtitle: '85234 Gilbert — 13 Curricula, 7 Co-ops, ESA Funding & Advanced Learner Focus',
    query: 'Homeschool Curriculum & Co-op Guide for a kid in zip code 85234. Advanced learner, grade acceleration, parent-chosen curriculum. 13 curricula, 7 co-op programs, cost analysis, AZ law & ESA, recommendations.',
    lens: 'standard',
    icon: 'GraduationCap',
    accentColor: 'amber',
    visibility: 'public',
    createdAt: '2026-02-13T18:10:00Z',
    contributor: 'mrshaun13',
    telemetry: {
      runStartedAt: '2026-02-13T18:10:00Z',
      runCompletedAt: '2026-02-13T18:52:00Z',
      durationMinutes: 42,
      includedSetup: false,
      skillVersion: '7.0',
      userPrompt: 'Homeschool Curriculum & Co-op Guide for a kid in zip code 85234. Advanced learner, grade acceleration, parent-chosen curriculum. 13 curricula, 7 co-op programs, cost analysis, AZ law & ESA, recommendations.',
      researchPlan: 'TOPIC: AZ Homeschool Curriculum & Co-op Guide — 85234 (Gilbert)\nTIME AXIS: Current (2025-2026 school year)\nPOPULATIONS: 13 curricula, 7 co-op programs near 85234\nCORE METRICS: Cost per year, advanced-friendliness, self-pacing, rigor, parent involvement, ESA coverage\nPROPOSED SECTIONS: Overview, Curriculum Comparison, Cost Analysis, Co-op Programs, AZ Law & ESA, Recommendations, Sources',
      checkpointModified: false,
      model: 'claude-sonnet-4-20250514',
      tokenUsage: null,
      searchesPerformed: 18,
      sourcesCount: 24,
      sectionsBuilt: 7,
      chartsBuilt: 5,
      filesGenerated: 11,
      productsCompared: null,
      dataPointsCollected: 420,
      phaseTiming: { environment: 1, interpret: 2, survey: 5, discover: 5, research: 12, analyze: 3, build: 12, present: 2 },
      contentAnalysis: {
        fleschKincaidGrade: 9.8,
        fleschKincaidLabel: '10th Grade',
        bloomsLevel: 5,
        bloomsLabel: 'Evaluate',
        bloomsRange: 'Understand → Evaluate',
        totalWords: 6800,
        totalSentences: 340,
        readabilityNote: 'Practical guide with decision frameworks, cost comparisons, and personalized recommendations for advanced learner homeschooling',
      },
      hoursSaved: {
        researchHours: 26.9,
        totalHoursSaved: 91.4,
        equivalentLabel: '~2.5 weeks full-time',
        productionHours: { 'interactive-dashboard': 64.5, 'white-paper': 42.4, 'blog-post': 22.5, 'technical-doc': 28.2, presentation: 13, 'github-repo': 43.5 },
      },
      consumptionTime: {
        estimatedMinutes: 62,
        readingMinutes: 45,
        chartExplorationMinutes: 3.75,
        interactiveOverheadMinutes: 9.75,
        estimatedLabel: '~62 min deep read',
      },
      promptComplexity: { wordCount: 28, entityCount: 5, ambiguityScore: 0.15 },
      sourceDiversityScore: 0.85,
      dataQualityDistribution: { t1: 168, t2: 210, t3: 30, t4: 12 },
    },
  },
];

export const projectComponents = {
  'cisco-history-dashboard': lazy(() => import('./cisco-history-dashboard/App')),
  'chainsaw-comparison': lazy(() => import('./chainsaw-comparison/App')),
  'limelight-history': lazy(() => import('./limelight-history/App')),
  'generator-comparison': lazy(() => import('./generator-comparison/App')),
  'homeschool-curriculum': lazy(() => import('./homeschool-curriculum/App')),
  'pixel-upgrade-analysis-mrshaun13': lazy(() => import('./pixel-upgrade-analysis-mrshaun13/App')),
  'ai-tooling-adoption-mrshaun13': lazy(() => import('./ai-tooling-adoption-mrshaun13/App')),
  'solar-system-explorer-mrshaun13': lazy(() => import('./solar-system-explorer-mrshaun13/App')),
  'traitors-s3-analytics-mrshaun13': lazy(() => import('./traitors-s3-analytics-mrshaun13/App')),
  'skill-showcase-mrshaun13': lazy(() => import('./skill-showcase-mrshaun13/App')),
  'coffee-beans-deep-dive-djagger': lazy(() => import('./coffee-beans-deep-dive-djagger/App')),
  'smart-telescope-finder-mrshaun13': lazy(() => import('./smart-telescope-finder-mrshaun13/App')),
  'career-pivot-explorer-mrshaun13': lazy(() => import('./career-pivot-explorer-mrshaun13/App')),
  'skill-architecture-v7-mrshaun13': lazy(() => import('./skill-architecture-v7-mrshaun13/App')),
  'az-homeschool-guide-mrshaun13': lazy(() => import('./az-homeschool-guide-mrshaun13/App')),
};
