import { lazy } from 'react';

export const projectRegistry = [
  {
    slug: 'cisco-history-dashboard',
    title: 'Cisco History Dashboard',
    subtitle: '40 Years of Innovation',
    query: 'Research the history of Cisco Systems from founding to present day',
    lens: 'standard',
    icon: 'Building2',
    accentColor: 'cyan',
    createdAt: '2026-02-08T12:00:00Z',
    telemetry: {
      runStartedAt: '2026-02-08T12:00:00Z',
      runCompletedAt: '2026-02-08T14:00:00Z',
      durationMinutes: 120,
      includedSetup: true,
      skillVersion: '3.0',
      userPrompt: 'Research the history of Cisco Systems from founding to present day',
      researchPlan: 'TOPIC: Cisco Systems Corporate History\nTIME AXIS: Decades — 1984-2026\nPOPULATIONS: Cisco as corporation, leadership eras, acquired companies\nCORE METRICS: Revenue, market cap, employee count, acquisitions\nTAXONOMIES: CEO eras (5), major acquisitions (20+), product lines\nPROPOSED SECTIONS: Overview, Financial Growth, Market Valuation, Workforce, Acquisitions, Leadership & Eras, Sources',
      checkpointModified: false,
      model: null,
      tokenUsage: null,
      searchesPerformed: 18,
      sourcesCount: 12,
      sectionsBuilt: 7,
      chartsBuilt: 10,
      filesGenerated: 12,
      productsCompared: null,
      dataPointsCollected: 180,
      phaseTiming: { environment: 3, interpret: 2, survey: 12, discover: 15, research: 35, analyze: 8, build: 35, present: 10 },
      contentAnalysis: {
        fleschKincaidGrade: 10.4,
        fleschKincaidLabel: '10th Grade',
        bloomsLevel: 4,
        bloomsLabel: 'Analyze',
        bloomsRange: 'Understand → Analyze',
        totalWords: 3800,
      },
      hoursSaved: {
        researchHours: 17.1,
        totalHoursSaved: 95.1,
        equivalentLabel: '~2.5 weeks full-time',
        productionHours: { 'interactive-dashboard': 78, 'white-paper': 35.8, 'blog-post': 27.5, 'technical-doc': 24.6, presentation: 15.5, 'github-repo': 47 },
      },
      consumptionTime: {
        estimatedMinutes: 39,
        estimatedLabel: '~40 min deep read',
      },
    },
  },
  {
    slug: 'chainsaw-comparison',
    title: 'Gas Chainsaw Comparison',
    subtitle: 'Product Comparison Dashboard',
    query: "I'm looking to buy a gas chainsaw for property maintenance",
    lens: 'product',
    icon: 'Axe',
    accentColor: 'orange',
    createdAt: '2026-02-09T12:00:00Z',
    telemetry: {
      runStartedAt: '2026-02-09T12:00:00Z',
      runCompletedAt: '2026-02-09T14:30:00Z',
      durationMinutes: 150,
      includedSetup: false,
      skillVersion: '3.0',
      userPrompt: "I'm looking to buy a gas chainsaw for property maintenance",
      researchPlan: "PRODUCT TYPE: Gas Chainsaw\nLIFECYCLE: Durable / Investment (5+ years)\nYOUR PROFILE: Homeowner, property maintenance, moderate budget\nPRODUCTS: 18 models across 6 brands\nTIERS: Entry/Homeowner, Farm & Ranch, Professional\nKEY SPECS: Displacement, HP, weight, bar length, noise, vibration, crankcase\nDERIVED METRICS: Power-to-weight ratio, Price per HP\nFLAGS: Ecosystem ✗, Multi-Use ✓, Features Matrix ✓, TCO ✓\nPROPOSED SECTIONS: Overview, Head-to-Head, Power & Weight, Value Analysis, Features Matrix, Use Case Fit, Recommendations, Sources",
      checkpointModified: false,
      model: null,
      tokenUsage: null,
      searchesPerformed: 24,
      sourcesCount: 18,
      sectionsBuilt: 8,
      chartsBuilt: 14,
      filesGenerated: 14,
      productsCompared: 18,
      dataPointsCollected: 324,
      phaseTiming: { environment: 1, interpret: 3, survey: 15, discover: 20, research: 50, analyze: 10, build: 40, present: 11 },
      contentAnalysis: {
        fleschKincaidGrade: 9.1,
        fleschKincaidLabel: '9th Grade',
        bloomsLevel: 5,
        bloomsLabel: 'Evaluate',
        bloomsRange: 'Understand → Evaluate',
        totalWords: 5200,
      },
      hoursSaved: {
        researchHours: 26,
        totalHoursSaved: 123,
        equivalentLabel: '~3 weeks full-time',
        productionHours: { 'interactive-dashboard': 97, 'white-paper': 44.2, 'blog-post': 34, 'technical-doc': 29.4, presentation: 19, 'github-repo': 59 },
      },
      consumptionTime: {
        estimatedMinutes: 54,
        estimatedLabel: '~55 min deep read',
      },
    },
  },
  {
    slug: 'limelight-history',
    title: 'Limelight Networks History',
    subtitle: 'Rise & Fall of a CDN Pioneer',
    query: 'Research the history of Limelight Networks the CDN',
    lens: 'standard',
    icon: 'Globe',
    accentColor: 'cyan',
    createdAt: '2026-02-10T05:53:00Z',
    telemetry: {
      runStartedAt: '2026-02-10T05:53:00Z',
      runCompletedAt: '2026-02-10T06:30:00Z',
      durationMinutes: 37,
      includedSetup: false,
      skillVersion: '4.0',
      userPrompt: 'Research the history of Limelight Networks the CDN',
      researchPlan: 'TOPIC: Rise & Fall of Limelight Networks (2001-2025)\nTIME AXIS: Technology Eras — 6 periods\nPOPULATIONS: Limelight/Edgio, CDN competitors, CDN industry\nCORE METRICS: Revenue, stock price, market share, network scale\nTAXONOMIES: Eras (6), acquisitions (7), legal events (13)\nPROPOSED SECTIONS: Overview, Financial Journey, Competitive Landscape, Events Timeline, Patent Wars, Acquisitions, The Collapse, Sources',
      checkpointModified: false,
      model: null,
      tokenUsage: null,
      searchesPerformed: 14,
      sourcesCount: 15,
      sectionsBuilt: 8,
      chartsBuilt: 8,
      filesGenerated: 11,
      productsCompared: null,
      dataPointsCollected: 220,
      phaseTiming: { environment: 0, interpret: 2, survey: 10, discover: 8, research: 25, analyze: 5, build: 30, present: 5 },
      contentAnalysis: {
        fleschKincaidGrade: 10.8,
        fleschKincaidLabel: '11th Grade',
        bloomsLevel: 4,
        bloomsLabel: 'Analyze',
        bloomsRange: 'Understand → Analyze',
        totalWords: 4200,
      },
      hoursSaved: {
        researchHours: 18.5,
        totalHoursSaved: 98,
        equivalentLabel: '~2.5 weeks full-time',
        productionHours: { 'interactive-dashboard': 80, 'white-paper': 37, 'blog-post': 28, 'technical-doc': 25, presentation: 16, 'github-repo': 48 },
      },
      consumptionTime: {
        estimatedMinutes: 42,
        estimatedLabel: '~42 min deep read',
      },
    },
  },
  {
    slug: 'generator-comparison',
    title: 'Generator Comparison',
    subtitle: 'Tri-Fuel & Dual-Fuel Home Backup',
    query: 'Research generators for home backup — tri-fuel with natural gas support, 3,300W to 15,000W range',
    lens: 'product',
    icon: 'Zap',
    accentColor: 'amber',
    createdAt: '2026-02-10T06:16:00Z',
    telemetry: {
      runStartedAt: '2026-02-10T06:16:00Z',
      runCompletedAt: '2026-02-10T06:50:00Z',
      durationMinutes: 34,
      includedSetup: false,
      skillVersion: '4.0',
      userPrompt: 'Research a generator for me. I want to eventually run natural gas to it but for now I will probably use gasoline. 3300w minimum up to ~15000w for whole home transfer switch. Gas furnace blower 650W, 3 refrigerators, 3 computers (1 gaming), networking gear, TVs. Summer: AC unit in Hendersonville TN.',
      researchPlan: 'PRODUCT TYPE: Tri-Fuel Portable Generator\nLIFECYCLE: Durable / Investment (5+ years)\nYOUR PROFILE: Homeowner, Hendersonville TN, gas furnace, 3 fridges, gaming PC, wants NG eventually, 3-ton AC in summer\nPRODUCTS: 12 models across 6 brands\nTIERS: Budget, Mid-Range, Whole-Home, Inverter\nKEY SPECS: Running watts (gas/NG/propane), engine cc, weight, noise, THD, runtime, fuel tank\nDERIVED METRICS: Watts-per-dollar (NG), NG-to-Gas ratio, Power-to-weight\nFLAGS: Ecosystem ✗, Multi-Use ✓, Features Matrix ✓, TCO ✓\nPROPOSED SECTIONS: Overview, Head-to-Head, Power Analysis, Value & Cost, Features Matrix, Recommendations, Sources',
      checkpointModified: false,
      model: null,
      tokenUsage: null,
      searchesPerformed: 16,
      sourcesCount: 14,
      sectionsBuilt: 7,
      chartsBuilt: 12,
      filesGenerated: 12,
      productsCompared: 12,
      dataPointsCollected: 288,
      phaseTiming: { environment: 0, interpret: 2, survey: 8, discover: 10, research: 30, analyze: 5, build: 25, present: 5 },
      contentAnalysis: {
        fleschKincaidGrade: 9.5,
        fleschKincaidLabel: '10th Grade',
        bloomsLevel: 5,
        bloomsLabel: 'Evaluate',
        bloomsRange: 'Understand → Evaluate',
        totalWords: 6200,
      },
      hoursSaved: {
        researchHours: 28,
        totalHoursSaved: 130,
        equivalentLabel: '~3.5 weeks full-time',
        productionHours: { 'interactive-dashboard': 102, 'white-paper': 46, 'blog-post': 36, 'technical-doc': 30, presentation: 20, 'github-repo': 62 },
      },
      consumptionTime: {
        estimatedMinutes: 58,
        estimatedLabel: '~1 hr deep read',
      },
    },
  },
  {
    slug: 'homeschool-curriculum',
    title: 'Homeschool Curriculum Guide',
    subtitle: 'Curricula & Co-op Programs for Advanced Learners',
    query: 'Research homeschool curricula and co-op programs near Hendersonville TN (37075) for an advanced child',
    lens: 'standard',
    icon: 'GraduationCap',
    accentColor: 'violet',
    createdAt: '2026-02-10T09:06:00Z',
    telemetry: {
      runStartedAt: '2026-02-10T09:06:00Z',
      runCompletedAt: '2026-02-10T09:50:00Z',
      durationMinutes: 44,
      includedSetup: false,
      skillVersion: '4.0',
      userPrompt: 'Research homeschool curricula for an advanced child moving from Three Oaks Academy to a choose-your-own-curriculum co-op model. Also research co-op programs near 37075 including CHET and Anchored at Long Hollow Church.',
      researchPlan: 'TOPIC: Homeschool Curriculum & Co-op Guide\nFOCUS: Advanced learner, grade acceleration, parent-chosen curriculum\nPOPULATIONS: 13 curricula, 7 co-op programs near 37075\nCORE METRICS: Cost, advanced-friendliness, self-pacing, parent involvement, grade range\nPROPOSED SECTIONS: Overview, Curriculum Comparison, Cost Analysis, Co-op Programs, CHET vs Anchored, Recommendations, Sources',
      checkpointModified: false,
      model: null,
      tokenUsage: null,
      searchesPerformed: 20,
      sourcesCount: 31,
      sectionsBuilt: 7,
      chartsBuilt: 3,
      filesGenerated: 10,
      productsCompared: null,
      dataPointsCollected: 260,
      phaseTiming: { environment: 1, interpret: 2, survey: 10, discover: 8, research: 15, analyze: 3, build: 20, present: 5 },
      contentAnalysis: {
        fleschKincaidGrade: 9.2,
        fleschKincaidLabel: '9th Grade',
        bloomsLevel: 5,
        bloomsLabel: 'Evaluate',
        bloomsRange: 'Understand → Evaluate',
        totalWords: 5800,
      },
      hoursSaved: {
        researchHours: 28.5,
        totalHoursSaved: 99.5,
        equivalentLabel: '~2.5 weeks full-time',
        productionHours: { 'interactive-dashboard': 71, 'white-paper': 40.9, 'blog-post': 20.5, 'technical-doc': 30.3, presentation: 12, 'github-repo': 46 },
      },
      consumptionTime: {
        estimatedMinutes: 48,
        estimatedLabel: '~50 min deep read',
      },
    },
  },
  {
    slug: 'pixel-upgrade-analysis-mrshaun13',
    title: 'Pixel 9 Pro Upgrade Analysis',
    subtitle: 'Should you upgrade? Tick-tock innovation cycles, cost analysis & verdict',
    query: 'Is it worth upgrading from the Pixel 9 Pro to a new Pixel phone right now?',
    lens: 'product',
    icon: 'Smartphone',
    accentColor: 'emerald',
    createdAt: '2026-02-10T18:23:00Z',
    telemetry: {
      runStartedAt: '2026-02-10T18:00:00Z',
      runCompletedAt: '2026-02-10T19:09:00Z',
      durationMinutes: 44,
      includedSetup: true,
      skillVersion: '5.1',
      userPrompt: 'I want to do research about if it is worth upgrading from the pixel 9 pro to a new pixel phone right now.',
      researchPlan: 'PRODUCT TYPE: Google Pixel Smartphone (Upgrade Analysis)\nPHONES COMPARED: 6 models (Pixel 6 Pro through 10 Pro)\nSECTIONS: Overview, Spec Comparison, Feature Delta, Innovation Cycles, Upgrade Cost, Pros & Cons, Recommendations, Sources',
      checkpointModified: true,
      model: null,
      tokenUsage: null,
      searchesPerformed: 8,
      sourcesCount: 12,
      sectionsBuilt: 8,
      chartsBuilt: 4,
      filesGenerated: 12,
      productsCompared: 6,
      dataPointsCollected: 264,
      phaseTiming: { environment: 15, interpret: 3, survey: 5, discover: 8, research: 10, analyze: 2, build: 20, present: 6 },
      contentAnalysis: {
        fleschKincaidGrade: 10.1,
        fleschKincaidLabel: '10th Grade',
        bloomsLevel: 5,
        bloomsLabel: 'Evaluate',
        bloomsRange: 'Understand → Evaluate',
        totalWords: 4500,
        totalSentences: 225,
        readabilityNote: 'Consumer-friendly product analysis with data-driven recommendations and decision frameworks',
      },
      hoursSaved: {
        researchHours: 16.3,
        totalHoursSaved: 82,
        equivalentLabel: '~2 weeks full-time',
        productionHours: { 'interactive-dashboard': 66, 'white-paper': 40.6, 'blog-post': 24, 'technical-doc': 27.6, presentation: 14, 'github-repo': 38 },
      },
      consumptionTime: {
        estimatedMinutes: 37,
        readingMinutes: 22.5,
        chartExplorationMinutes: 10,
        interactiveOverheadMinutes: 4,
        estimatedLabel: '~35 min deep read',
      },
    },
  },
  {
    slug: 'ai-tooling-adoption-mrshaun13',
    title: 'AI Developer Tooling Adoption',
    subtitle: 'Hype vs Reality — Agents, MCP, Skills & the Adoption Paradox',
    query: 'Research the adoption rate of modern AI developer tooling — agents, MCP servers, skills/workflows, AGENTS.md. Is it really on a huge climb or still slow? Include future projections.',
    lens: 'standard',
    icon: 'Brain',
    accentColor: 'cyan',
    createdAt: '2026-02-10T22:49:00Z',
    telemetry: {
      runStartedAt: '2026-02-10T22:00:00Z',
      runCompletedAt: '2026-02-10T23:15:00Z',
      durationMinutes: 75,
      includedSetup: false,
      skillVersion: '5.1',
      userPrompt: 'I want to research the adoption rate of the more modern AI tooling that exists that are considered the game changing ways of using an AI agent. agents.md, skills.md, MCP servers. Is it really on a huge climb or is it still really slow? Include future projections.',
      researchPlan: 'TOPIC: Adoption Rate of Modern AI Developer Tooling — Hype vs Reality\nTIME AXIS: Technology Eras (Pre-Copilot, Copilot Era, Chat-Augmented, Agentic Explosion)\nCATEGORIES: AI Coding Assistants, Agentic Coding, MCP Servers, Agent Instruction Files, Skills & Workflows\nCORE METRICS: User growth, revenue, developer survey adoption, GitHub stars, enterprise adoption, sentiment/trust, productivity impact, market projections\nHYPE VS REALITY: Scorecard with gap analysis\nPROPOSED SECTIONS: Overview, Growth Timelines, Reality Check, Tool Deep Dive, Enterprise vs Individual, Future Projections, Sources',
      checkpointModified: false,
      model: null,
      tokenUsage: null,
      searchesPerformed: 12,
      sourcesCount: 15,
      sectionsBuilt: 7,
      chartsBuilt: 12,
      filesGenerated: 11,
      productsCompared: null,
      dataPointsCollected: 300,
      phaseTiming: { environment: 2, interpret: 3, survey: 10, discover: 10, research: 15, analyze: 5, build: 25, present: 5 },
      contentAnalysis: {
        fleschKincaidGrade: 10.5,
        fleschKincaidLabel: '11th Grade',
        bloomsLevel: 5,
        bloomsLabel: 'Evaluate',
        bloomsRange: 'Understand → Evaluate',
        totalWords: 7377,
        totalSentences: 369,
        readabilityNote: 'Data-driven analysis with hype-vs-reality framework and multi-dimensional adoption metrics',
      },
      hoursSaved: {
        researchHours: 20.25,
        totalHoursSaved: 103.75,
        equivalentLabel: '~2.5 weeks full-time',
        productionHours: { 'interactive-dashboard': 83.5, 'white-paper': 43.5, 'blog-post': 29.5, 'technical-doc': 25.5, presentation: 16.5, 'github-repo': 51.5 },
      },
      consumptionTime: {
        estimatedMinutes: 70,
        readingMinutes: 49.2,
        chartExplorationMinutes: 9,
        interactiveOverheadMinutes: 11.6,
        estimatedLabel: '~1 hr deep read',
      },
    },
  },
  {
    slug: 'coffee-beans-deep-dive-djagger',
    title: 'Coffee Beans Deep Dive',
    subtitle: 'Species, varieties, caffeine, flavor, rarity & global production',
    query: 'Research the different types of coffee beans — quality, flavor, caffeine, which keep you awake most, international varieties, rare beans',
    lens: 'standard',
    icon: 'Coffee',
    accentColor: 'amber',
    createdAt: '2026-02-10T22:57:00Z',
    telemetry: {
      runStartedAt: '2026-02-10T22:57:00Z',
      runCompletedAt: '2026-02-10T23:15:00Z',
      durationMinutes: 18,
      includedSetup: true,
      skillVersion: '6.0',
      userPrompt: 'Research the different types of coffee beans and which ones are highest quality, rating flavor and caffeine amount, which ones keep you awake the most vs which ones don\'t. Do a deep dive into coffee beans all types of them, internationally, easy to get, rare, etc.',
      researchPlan: 'TOPIC: Coffee Beans — Global Taxonomy & Comparison\nTIME AXIS: Not time-dependent (taxonomic study)\nPOPULATIONS: 4 species, 15 Arabica varieties, 10 rare coffees, 10 producing countries\nCORE METRICS: Caffeine content, flavor rating, cupping score, price, production volume\nTAXONOMIES: Species (4), Arabica varieties (15), rare coffees (10), processing methods (5)\nPROPOSED SECTIONS: Overview, Caffeine & Alertness, Flavor Profiles, Arabica Varieties, Rare & Expensive, Global Production, Processing Methods, Sources',
      checkpointModified: false,
      model: 'claude-sonnet',
      tokenUsage: null,
      searchesPerformed: 8,
      sourcesCount: 12,
      sectionsBuilt: 8,
      chartsBuilt: 12,
      filesGenerated: 11,
      productsCompared: null,
      dataPointsCollected: 285,
      phaseTiming: { environment: 5, interpret: 1, survey: 3, discover: 2, research: 3, analyze: 1, build: 8, present: 2 },
      contentAnalysis: {
        fleschKincaidGrade: 10,
        fleschKincaidLabel: '10th Grade',
        bloomsLevel: 4,
        bloomsLabel: 'Analyze',
        bloomsRange: 'Understand → Analyze',
        totalWords: 4800,
      },
      hoursSaved: {
        researchHours: 14,
        totalHoursSaved: 78,
        equivalentLabel: '~2 weeks full-time',
        productionHours: { 'interactive-dashboard': 62, 'white-paper': 32, 'blog-post': 22, 'technical-doc': 20, presentation: 12, 'github-repo': 40 },
      },
      consumptionTime: {
        estimatedMinutes: 25,
        estimatedLabel: '~25 min deep read',
      },
    },
  },
  {
    slug: 'coffee-beans-deep-dive-djagger',
    title: 'Coffee Beans Deep Dive',
    subtitle: 'Species, varieties, caffeine, flavor, rarity & global production',
    query: 'Research the different types of coffee beans — quality, flavor, caffeine, which keep you awake most, international varieties, rare beans',
    lens: 'standard',
    icon: 'Coffee',
    accentColor: 'amber',
    createdAt: '2026-02-10T22:57:00Z',
    telemetry: {
      runStartedAt: '2026-02-10T22:57:00Z',
      runCompletedAt: '2026-02-10T23:15:00Z',
      durationMinutes: 18,
      includedSetup: true,
      skillVersion: '6.0',
      userPrompt: 'Research the different types of coffee beans and which ones are highest quality, rating flavor and caffeine amount, which ones keep you awake the most vs which ones don\'t. Do a deep dive into coffee beans all types of them, internationally, easy to get, rare, etc.',
      researchPlan: 'TOPIC: Coffee Beans — Global Taxonomy & Comparison\nTIME AXIS: Not time-dependent (taxonomic study)\nPOPULATIONS: 4 species, 15 Arabica varieties, 10 rare coffees, 10 producing countries\nCORE METRICS: Caffeine content, flavor rating, cupping score, price, production volume\nTAXONOMIES: Species (4), Arabica varieties (15), rare coffees (10), processing methods (5)\nPROPOSED SECTIONS: Overview, Caffeine & Alertness, Flavor Profiles, Arabica Varieties, Rare & Expensive, Global Production, Processing Methods, Sources',
      checkpointModified: false,
      model: 'claude-sonnet',
      tokenUsage: null,
      searchesPerformed: 8,
      sourcesCount: 12,
      sectionsBuilt: 8,
      chartsBuilt: 12,
      filesGenerated: 11,
      productsCompared: null,
      dataPointsCollected: 285,
      phaseTiming: { environment: 5, interpret: 1, survey: 3, discover: 2, research: 3, analyze: 1, build: 8, present: 2 },
      contentAnalysis: {
        fleschKincaidGrade: 10,
        fleschKincaidLabel: '10th Grade',
        bloomsLevel: 4,
        bloomsLabel: 'Analyze',
        bloomsRange: 'Understand → Analyze',
        totalWords: 4800,
      },
      hoursSaved: {
        researchHours: 14,
        totalHoursSaved: 78,
        equivalentLabel: '~2 weeks full-time',
        productionHours: { 'interactive-dashboard': 62, 'white-paper': 32, 'blog-post': 22, 'technical-doc': 20, presentation: 12, 'github-repo': 40 },
      },
      consumptionTime: {
        estimatedMinutes: 25,
        estimatedLabel: '~25 min deep read',
      },
    },
  },
  {
    slug: 'solar-system-explorer-mrshaun13',
    title: 'Solar System Explorer',
    subtitle: 'An Interactive Space Adventure for Kids — All 8 Planets + Pluto!',
    query: 'Build a cool learning experience for a seven-year-old advanced first grader to learn about our solar system with the ability to zoom in to all the planets and see every stat about their size and everything.',
    lens: 'standard',
    icon: 'Globe',
    accentColor: 'blue',
    createdAt: '2026-02-11T03:48:00Z',
    telemetry: {
      runStartedAt: '2026-02-11T03:46:00Z',
      runCompletedAt: '2026-02-11T16:45:00Z',
      durationMinutes: 180,
      includedSetup: false,
      skillVersion: '6.1',
      userPrompt: 'Build a cool learning experience for a seven-year-old advanced first grader to learn about our solar system with the ability to zoom in to all the planets and see every stat about their size and everything. Add a funny dad joke per planet too.',
      researchPlan: 'TOPIC: Our Solar System — An Interactive Space Explorer for Kids\nAUDIENCE: 7-year-old advanced first grader\nPLANETS: All 8 + Sun + Pluto\nGROUPING: Inner Rocky vs Outer Giants\nKEY STATS: Distance, diameter, day/year length, gravity, temperature, moons, atmosphere, fun facts, dad jokes, exploration history\nSECTIONS: Mission Control, Planet Explorer, Space Records (7 sub-tabs), Size Showdown, Hot & Cold, Gravity Playground, Race to the Sun, Earth Moon & Seasons, Night Sky, Space Events, Space Timeline, Trivia Game, Space Lab, Space Library\nINTERACTIVES: Wind Race Game, Time Converter, Spinning Planet Comparator, Gravity Calculator, Distance Race, Constellation Viewer, Trivia Game',
      checkpointModified: true,
      model: null,
      tokenUsage: null,
      searchesPerformed: 5,
      sourcesCount: 8,
      sectionsBuilt: 14,
      chartsBuilt: 22,
      filesGenerated: 23,
      productsCompared: null,
      dataPointsCollected: 620,
      phaseTiming: { environment: 1, interpret: 1, survey: 2, discover: 1, research: 2, analyze: 1, build: 160, present: 12 },
      contentAnalysis: {
        fleschKincaidGrade: 3.5,
        fleschKincaidLabel: '3rd–4th Grade',
        bloomsLevel: 3,
        bloomsLabel: 'Apply',
        bloomsRange: 'Remember → Apply',
        totalWords: 9200,
        totalSentences: 780,
        readabilityNote: 'Kid-friendly space exploration with interactive games, animated comparisons, real-world analogies, and hands-on learning for a 7-year-old audience. Includes wind speed race game, planet time converter, spinning planet comparator, and rich record book.',
      },
      hoursSaved: {
        researchHours: 12,
        totalHoursSaved: 98,
        equivalentLabel: '~2.5 weeks full-time',
        productionHours: { 'interactive-dashboard': 86, 'white-paper': 38, 'blog-post': 26, 'technical-doc': 28, presentation: 16, 'github-repo': 52 },
      },
      consumptionTime: {
        estimatedMinutes: 75,
        readingMinutes: 36,
        chartExplorationMinutes: 16.5,
        interactiveOverheadMinutes: 22.5,
        estimatedLabel: '~75 min fun exploration',
      },
    },
  },,
];

export const projectComponents = {
  'cisco-history-dashboard': lazy(() => import('./cisco-history-dashboard/App')),
  'chainsaw-comparison': lazy(() => import('./chainsaw-comparison/App')),
  'limelight-history': lazy(() => import('./limelight-history/App')),
  'generator-comparison': lazy(() => import('./generator-comparison/App')),
  'homeschool-curriculum': lazy(() => import('./homeschool-curriculum/App')),
  'pixel-upgrade-analysis-mrshaun13': lazy(() => import('./pixel-upgrade-analysis-mrshaun13/App')),
  'ai-tooling-adoption-mrshaun13': lazy(() => import('./ai-tooling-adoption-mrshaun13/App')),
  'solar-system-explorer-mrshaun13': lazy(() => import('./solar-system-explorer-mrshaun13/App')),
};